title: JG
author:
  name: JG
  email: your-email@domain.com

description: >
  My personal website after many years without one.

# Disable the standard theme
# theme: minima 

# Fetch the latest version directly from GitHub
remote_theme: "jekyll/minima"

# Required for remote themes to work on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: solarized

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: true

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
    - title: JG on LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/company/github"

  hide_site_feed_link: true
